### ISSUE TITLE
Could you move all the code into a namespace?

### ISSUE THREAD

**Issue by pelikhan** [robo-technical-group/pxt-arcade-mazes#1]
Interfaces and enums can stay in the global namespace but use prefix "Maze"... Otherwise, it's best to add to the ``maze`` namespace.

**Comment by alex-kulcsar** [comment]
@pelikhan ! I'm just now seeing this. I'm refactoring the code now; update coming shortly.

**Comment by alex-kulcsar** [comment]
Resolved in version [2.1.0](https://github.com/robo-technical-group/pxt-arcade-mazes/releases/tag/v2.1.0). Thanks, Peli!
